<div class="container">
  <div class="row">
		<div class="col--md-6 offset-md-3">
			<div class="container">
				<form method="post" action="signup/register">
					<div class="form-group">
						<label for="nombre">Nombre</label>
						<input required id="nombre" name="nombre" type="text" class="form-control" placeholder="Enter nombre">
					</div>
					<div class="form-group">
						<label for="apPaterno">Apellido paterno</label>
						<input required id="apPaterno" name="apPaterno" type="text" class="form-control" placeholder="Enter apPaterno">
					</div>
					<div class="form-group">
						<label for="apMaterno">Apellido materno</label>
						<input required id="apMaterno" name="apMaterno" type="text" class="form-control" placeholder="Enter apMaterno">
					</div>
					<div class="form-group">
						<label for="sexo">Sexo</label>
						<select id="sexo" name="sexo" type="text" class="form-control" placeholder="Enter sexo">
							<option value="m">Masculino</option>
							<option value="f">Femenino</option>
						</select>
					</div>
					<div class="form-group">
						<label for="fechaNac">Fecha de nacimiento</label>
						<input required id="fechaNac" name="fechaNac" type="text" class="form-control" placeholder="Enter fechaNac">
					</div>
					<div class="form-group">
						<label for="usuario">Usuario</label>
						<input required id="usuario" name="usuario" type="text" class="form-control" placeholder="Enter usuario">
					</div>
					<div class="form-group">
						<label for="pswd">Password</label>
						<input required id="pswd" name="pswd" type="password" class="form-control" placeholder="Password">
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
  </div>
</div>
